version: '3'
services:
  app:
    image: tomcat:8.5.51-jdk8-openjdk
    container_name: myapp
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    ports:
      - 80:8080
      - 8000:8000
    command: catalina.sh jpda run
networks:
  default:
    external:
      name: mynw
